function cutImageLoad() {
    imageKR()
    imageEN()
}

function imageKR() {
    //KR
    cut0 = loadImage('cut_image/cut0.png');
    cut1 = loadImage('cut_image/cut1.PNG')
    cut2 = loadImage('cut_image/cut2.PNG')
    cut3 = loadImage('cut_image/cut3.PNG')
    cut4 = loadImage('cut_image/cut4.PNG')
    cut5 = loadImage('cut_image/cut5.PNG')
    cut6 = loadImage('cut_image/cut6.PNG')
    cut7 = loadImage('cut_image/cut7.PNG')
    cut8 = loadImage('cut_image/cut8.PNG')
    cut9 = loadImage('cut_image/cut9.PNG')
    cut10 = loadImage('cut_image/cut10.PNG')
    cut11 = loadImage('cut_image/cut11.PNG')
    cut12 = loadImage('cut_image/cut12.PNG')
    cut13 = loadImage('cut_image/cut13.PNG')
    cut14 = loadImage('cut_image/cut14.jpg')
    cut15 = loadImage('cut_image/cut15.jpg')
    cut16 = loadImage('cut_image/cut16.jpg')
    cut17 = loadImage('cut_image/cut17.jpg')
    cut18 = loadImage('cut_image/cut18.jpg')
    
    cut19 = loadImage('cut_image/cut19.PNG')
    cut20 = loadImage('cut_image/cut20.PNG')
    cut21 = loadImage('cut_image/cut21.PNG')
    cut22 = loadImage('cut_image/cut22.PNG')
    cut23 = loadImage('cut_image/cut23.PNG')
    cut24 = loadImage('cut_image/cut24.PNG')
    cut25 = loadImage('cut_image/cut25.PNG')
    cut26 = loadImage('cut_image/cut26.PNG')
    cut27 = loadImage('cut_image/cut27.PNG')
    cut28 = loadImage('cut_image/cut28.png')
    cut29 = loadImage('cut_image/cut29.PNG')
    cut30 = loadImage('cut_image/cut30.PNG')
}
function imageEN() {
    //EN
    cutE0 = loadImage('cut_English/cutE_0.JPG')
    cutE1 = loadImage('cut_English/cutE_1.JPG')
    cutE2 = loadImage('cut_English/cutE_2.JPG')
    cutE3 = loadImage('cut_English/cutE_3.JPG')
    cutE4 = loadImage('cut_English/cutE_4.JPG')
    cutE5 = loadImage('cut_English/cutE_5.JPG')
    cutE6 = loadImage('cut_English/cutE_6.JPG')
    cutE7 = loadImage('cut_English/cutE_7.JPG')
    cutE8 = loadImage('cut_English/cutE_8.JPG')
    cutE9 = loadImage('cut_English/cutE_9.JPG')
    cutE10 = loadImage('cut_English/cutE_10.JPG')
    cutE11 = loadImage('cut_English/cutE_11.JPG')
    cutE12 = loadImage('cut_English/cutE_12.JPG')
    cutE13 = loadImage('cut_English/cutE_13.JPG')
    cutE14 = loadImage('cut_English/cutE_14.JPG')
    cutE15 = loadImage('cut_English/cutE_15.JPG')
    cutE16 = loadImage('cut_English/cutE_16.JPG')
    cutE17 = loadImage('cut_English/cutE_17.jpg')
    cutE18 = loadImage('cut_English/cutE_18.JPG')  
    cutE19 = loadImage('cut_English/cutE_19.JPG')
    cutE20 = loadImage('cut_English/cutE_20.JPG')   
    cutE21 = loadImage('cut_English/cutE_21.JPG')   
    cutE22 = loadImage('cut_English/cutE_22.JPG')   
    cutE23 = loadImage('cut_English/cutE_23.JPG')   
    cutE24 = loadImage('cut_English/cutE_24.JPG')   
    cutE25 = loadImage('cut_English/cutE_25.JPG')
    cutE26 = loadImage('cut_English/cutE_26.JPG')
    cutE27 = loadImage('cut_English/cutE_27.JPG')
    cutE28 = loadImage('cut_English/cutE_28.JPG')
    cutE29 = loadImage('cut_English/cutE_29.JPG')
    cutE30 = loadImage('cut_English/cutE_30.JPG')
}